name: Publish to Marketplace

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Bump version
        run: |
          git config user.email ${{ secrets.USER_EMAIL }}
          git config user.name ${{ secrets.USER_NAME }}
          npm version patch --no-git-tag-version
          echo "##vso[task.setvariable variable=EXTENSION_VERSION]$(npm --no-git-tag-version version)"
          git add package.json
          git commit -m "Bump version"
          git push

      - name: Publish Extension
        run: |
          npx vsce publish -p ${{ secrets.MARKETPLACE_TOKEN }}
